# """Ejercicios de tuplas"""
# print("Ejercicio 1:")
# tupladenum=(1,2,3,4,5)
# print("tupla de números:",tupladenum)
# print("Ejercicio 2:")
# print("El segundo valor de la tupla es:",tupladenum[1])
# print("Ejercicio 3:")
# print("La longitud de la tupla es:",len(tupladenum))
# print("Ejercicio 4:")
# print("La posición del número 4 en la tupla es:",tupladenum.index(4))
# print("Ejercicio 5:")
# print("Las veces que aparece el número 2 es:",tupladenum.count(2))
# print("Ejercicio 6:")
# tpltxtnm=("Hoy","es",10,"de","mayo","del",2025)
# print("tupla de tipos mezclados:",tpltxtnm)
# print("Ejercicio 7:")
# tplex=(1,2,3,4,5,(6,7,8,9,10))
# tplin=tplex[5][0]
# print("primer valor de la tupla dentro de una tupla:",tplin)